# Generated by Django 4.2.6 on 2024-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
