# Generated by Django 4.2.6 on 2024-02-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_producttable_image_carttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carttable',
            name='pid',
            field=models.ForeignKey(db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttable'),
        ),
        migrations.AlterField(
            model_name='carttable',
            name='uid',
            field=models.ForeignKey(db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
